export const privacyPolicy = {
  ru: [
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Ваша конфиденциальность важна для нас. В этом документе объясняется, какие данные мы собираем и как мы их используем.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '1. Сбор информации',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Мы собираем информацию, которую вы предоставляете при регистрации: имя пользователя, адрес электронной почты и данные профиля. Также мы собираем технические данные о вашем устройстве и использовании сайта.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '2. Использование данных',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Мы используем собранные данные для обеспечения работы сервиса, улучшения пользовательского опыта и связи с вами. Мы не продаем ваши личные данные третьим лицам.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '3. Файлы cookie',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Мы используем файлы <strong>cookie</strong> для сохранения ваших предпочтений и анализа трафика. Вы можете отключить <strong>cookie</strong> в настройках своего браузера.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '4. Защита информации',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Мы принимаем все необходимые меры для защиты ваших данных от несанкционированного доступа. Однако ни один метод передачи данных через интернет не является на 100% безопасным.',
      isEmpty: false,
      settings: {},
    },
  ],
  en: [
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Your privacy is important to us. This document explains what data we collect and how we use it.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '1. Data Collection',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'We collect information you provide when registering: username, email address, and profile data. We also collect technical data about your device and site usage.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '2. Use of Data',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'We use the collected data to provide the service, improve user experience, and communicate with you. We do not sell your personal data to third parties.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '3. Cookies',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'We use <strong>cookies</strong> to save your preferences and analyze traffic. You can disable <strong>cookies</strong> in your browser settings.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '4. Data Protection',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'We take all necessary measures to protect your data from unauthorized access. However, no method of data transmission over the Internet is 100% secure.',
      isEmpty: false,
      settings: {},
    },
  ],
};
