export const termsOfService = {
  ru: [
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Добро пожаловать в Circlo. Используя нашу платформу, вы соглашаетесь с данными условиями. Пожалуйста, внимательно ознакомьтесь с ними.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '1. Принятие условий',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Регистрируясь на сайте или используя любые его функции, вы подтверждаете свое полное согласие с настоящими Условиями. Если вы не согласны с каким-либо пунктом, вы должны прекратить использование платформы.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '2. Регистрация и аккаунт',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Вы несете ответственность за безопасность своего аккаунта и за все действия, совершенные под вашими учетными данными. Мы оставляем за собой право приостановить доступ к аккаунту в случае нарушения правил.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '3. Контент пользователя',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Вы сохраняете права на контент, который публикуете, но предоставляете Circlo неисключительную лицензию на его отображение и распространение в рамках платформы.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '4. Ограничение ответственности',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Платформа предоставляется по принципу <strong>"как есть"</strong>. Мы не гарантируем бесперебойную работу и не несем ответственности за возможные убытки, связанные с использованием сервиса.',
      isEmpty: false,
      settings: {},
    },
  ],
  en: [
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'Welcome to Circlo. By using our platform, you agree to these terms. Please read them carefully.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '1. Acceptance of Terms',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'By registering on the site or using any of its features, you confirm your full agreement with these Terms. If you do not agree with any point, you must stop using the platform.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '2. Registration and Account',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'You are responsible for the security of your account and for all actions taken under your credentials. We reserve the right to suspend account access in case of violation of the rules.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '3. User Content',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'You retain rights to the content you post, but grant Circlo a non-exclusive license to display and distribute it within the platform.',
      isEmpty: false,
      settings: {},
    },
    {
      id: crypto.randomUUID(),
      type: 'heading',
      content: '4. Limitation of Liability',
      isEmpty: false,
      settings: { level: 2 },
    },
    {
      id: crypto.randomUUID(),
      type: 'paragraph',
      content: 'The platform is provided on an <strong>"as is"</strong> basis. We do not guarantee uninterrupted operation and are not responsible for any losses associated with the use of the service.',
      isEmpty: false,
      settings: {},
    },
  ],
};
